// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL-kN9-zNlSEk_bptw48KZvTxaM5-dPZo',
    appId: '1:315961273637:web:a238e9f5b7fca9ed23fecc',
    messagingSenderId: '315961273637',
    projectId: 'aplikasibantuancheck',
    authDomain: 'aplikasibantuancheck.firebaseapp.com',
    storageBucket: 'aplikasibantuancheck.firebasestorage.app',
    measurementId: 'G-SJWNCCP643',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJj8QGo1whqJkH3bTak-vMBOTMob-lQI',
    appId: '1:315961273637:android:ba0a4f34d4f69ce723fecc',
    messagingSenderId: '315961273637',
    projectId: 'aplikasibantuancheck',
    storageBucket: 'aplikasibantuancheck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT10o4MjO4NgBku_WzyDYwsMDQtbDTxIg',
    appId: '1:315961273637:ios:9a46e95cdc18269723fecc',
    messagingSenderId: '315961273637',
    projectId: 'aplikasibantuancheck',
    storageBucket: 'aplikasibantuancheck.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiBantuanCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT10o4MjO4NgBku_WzyDYwsMDQtbDTxIg',
    appId: '1:315961273637:ios:9a46e95cdc18269723fecc',
    messagingSenderId: '315961273637',
    projectId: 'aplikasibantuancheck',
    storageBucket: 'aplikasibantuancheck.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiBantuanCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL-kN9-zNlSEk_bptw48KZvTxaM5-dPZo',
    appId: '1:315961273637:web:2159640777e1582b23fecc',
    messagingSenderId: '315961273637',
    projectId: 'aplikasibantuancheck',
    authDomain: 'aplikasibantuancheck.firebaseapp.com',
    storageBucket: 'aplikasibantuancheck.firebasestorage.app',
    measurementId: 'G-M6LXNP6D4F',
  );

}